In [40]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style('whitegrid')
plt.rcParams['axes.unicode_minus'] = False

%matplotlib inline

In [41]:
df = pd.read_csv('data\computer_prices_all.csv')
df.head(3)

,device_type,brand,model,release_year,os,form_factor,cpu_brand,cpu_model,cpu_tier,cpu_cores,...,resolution,refresh_hz,battery_wh,charger_watts,psu_watts,wifi,bluetooth,weight_kg,warranty_months,price
0,Desktop,Samsung,Samsung Forge XDI,2022,Windows,ATX,Intel,Intel i5-11129,3,12,...,2560x1440,90,0,0,750,Wi-Fi 6,5.1,11.00,36,1383.99
1,Laptop,Samsung,Samsung Pro KM8,2022,Windows,Mainstream,Intel,Intel i7-11114,4,12,...,1920x1080,90,56,120,0,Wi-Fi 6,5.3,2.03,12,2274.99
2,Desktop,Lenovo,Lenovo Strix BIE,2024,macOS,SFF,AMD,AMD Ryzen 5 5168,2,8,...,3440x1440,120,0,0,850,Wi-Fi 6,5.0,7.00,24,1879.99

In [42]:
print(type(df.info()))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 33 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   device_type          100000 non-null  object
 1   brand                100000 non-null  object
 2   model                100000 non-null  object
 3   release_year         100000 non-null  int64
 4   os                   100000 non-null  object
 5   form_factor          100000 non-null  object
 6   cpu_brand            100000 non-null  object
 7   cpu_model            100000 non-null  object
 8   cpu_tier             100000 non-null  int64
 9   cpu_cores            100000 non-null  int64
 10  cpu_threads          100000 non-null  int64
 11  cpu_base_ghz         100000 non-null  float64
 12  cpu_boost_ghz        100000 non-null  float64
 13  gpu_brand            100000 non-null  object
 14  gpu_model            100000 non-null  object
 15  gpu_tier             100000 non-null  int64
 16  vram_gb              100000 non-null  int64
 17  ram_gb               100000 non-null  int64
 18  storage_type         100000 non-null  object
 19  storage_gb           100000 non-null  int64
 20  storage_drive_count  100000 non-null  int64
 21  display_type         100000 non-null  object
 22  display_size_in      100000 non-null  float64
 23  resolution           100000 non-null  object
 24  refresh_hz           100000 non-null  int64
 25  battery_wh           100000 non-null  int64
 26  charger_watts        100000 non-null  int64
 27  psu_watts            100000 non-null  int64
 28  wifi                 100000 non-null  object
 29  bluetooth            100000 non-null  float64
 30  weight_kg            100000 non-null  float64
 31  warranty_months      100000 non-null  int64
 32  price                100000 non-null  float64
dtypes: float64(6), int64(14), object(13)
memory usage: 25.2+ MB
<class 'NoneType'>

In [43]:
df['cpu_model'].value_counts()

cpu_model
Apple M2 Pro        1389
Apple M1            1374
Apple M2 Max        1367
Apple M1 Pro        1341
Apple M3 Pro        1315
                    ...
AMD Ryzen 9 4286       1
Intel i9-10666         1
AMD Ryzen 9 5907       1
AMD Ryzen 3 4275       1
Intel i9-10449         1
Name: count, Length: 26971, dtype: int64

In [44]:
df = df.drop(columns=['device_type', 'model', 'wifi', 'bluetooth', 'storage_type', 'os', 'cpu_brand', 'form_factor'] + ['cpu_model'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 24 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   brand                100000 non-null  object
 1   release_year         100000 non-null  int64
 2   cpu_tier             100000 non-null  int64
 3   cpu_cores            100000 non-null  int64
 4   cpu_threads          100000 non-null  int64
 5   cpu_base_ghz         100000 non-null  float64
 6   cpu_boost_ghz        100000 non-null  float64
 7   gpu_brand            100000 non-null  object
 8   gpu_model            100000 non-null  object
 9   gpu_tier             100000 non-null  int64
 10  vram_gb              100000 non-null  int64
 11  ram_gb               100000 non-null  int64
 12  storage_gb           100000 non-null  int64
 13  storage_drive_count  100000 non-null  int64
 14  display_type         100000 non-null  object
 15  display_size_in      100000 non-null  float64
 16  resolution           100000 non-null  object
 17  refresh_hz           100000 non-null  int64
 18  battery_wh           100000 non-null  int64
 19  charger_watts        100000 non-null  int64
 20  psu_watts            100000 non-null  int64
 21  weight_kg            100000 non-null  float64
 22  warranty_months      100000 non-null  int64
 23  price                100000 non-null  float64
dtypes: float64(5), int64(14), object(5)
memory usage: 18.3+ MB

In [45]:
df.describe().round(2)

,release_year,cpu_tier,cpu_cores,cpu_threads,cpu_base_ghz,cpu_boost_ghz,gpu_tier,vram_gb,ram_gb,storage_gb,storage_drive_count,display_size_in,refresh_hz,battery_wh,charger_watts,psu_watts,weight_kg,warranty_months,price
count,100000.00,100000.00,100000.00,100000.00,100000.00,100000.00,100000.00,100000.00,100000.00,100000.00,100000.00,100000.00,100000.00,100000.00,100000.00,100000.00,100000.00,100000.00,100000.00
mean,2022.32,3.15,10.52,19.37,2.59,3.53,2.99,6.15,39.71,903.94,1.52,20.13,98.46,41.81,61.38,272.52,4.29,22.20,1928.76
std,2.03,1.37,5.04,9.72,0.34,0.35,1.46,3.96,31.90,774.24,0.80,6.71,43.30,35.87,62.80,354.69,3.81,10.23,580.49
min,2018.00,1.00,4.00,4.00,2.00,2.80,1.00,0.00,8.00,256.00,1.00,13.30,60.00,0.00,0.00,0.00,0.92,12.00,372.99
25%,2021.00,2.00,6.00,12.00,2.40,3.30,2.00,4.00,16.00,512.00,1.00,14.00,60.00,0.00,0.00,0.00,1.50,12.00,1503.99
50%,2023.00,3.00,8.00,16.00,2.60,3.50,3.00,6.00,32.00,512.00,1.00,16.00,90.00,56.00,65.00,0.00,2.00,24.00,1863.99
75%,2024.00,4.00,14.00,24.00,2.80,3.80,4.00,8.00,64.00,1024.00,2.00,27.00,120.00,70.00,90.00,650.00,7.00,24.00,2287.99
max,2025.00,6.00,28.00,56.00,3.40,4.50,6.00,16.00,144.00,4096.00,4.00,34.00,240.00,99.00,240.00,1200.00,16.00,48.00,10984.99

In [46]:
non_numeric = list(df.select_dtypes('object').columns)
non_numeric = non_numeric + ['cpu_tier', 'release_year']
non_numeric

['brand',
 'gpu_brand',
 'gpu_model',
 'display_type',
 'resolution',
 'cpu_tier',
 'release_year']

In [47]:
for col in non_numeric:
    print(df[col].nunique())

10
4
49
6
6
6
8

In [55]:
df['release_year'].value_counts()

release_year
2023    18020
2024    17969
2022    16054
2025    15835
2021    12016
2020     7986
2019     7090
2018     5030
Name: count, dtype: int64

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

one-hot = ['brand', 'gpu_brand', 'display_type']

oe_release_year = OrdinalEncoder(categories=[[0, 1, 2, 3, 4, 5, 6, 7, 8]])

df_non_num_enc = pd.get_dummies(df, columns=one-hot, drop_first=True, dtype=int)
df_non_num_enc

,release_year,cpu_tier,cpu_cores,cpu_threads,cpu_base_ghz,cpu_boost_ghz,gpu_model,gpu_tier,vram_gb,ram_gb,...,brand_Razer,brand_Samsung,gpu_brand_Apple,gpu_brand_Intel,gpu_brand_NVIDIA,display_type_LED,display_type_Mini-LED,display_type_OLED,display_type_QLED,display_type_VA
0,2022,3,12,24,2.8,3.8,RTX 40 60,2,6,16,...,0,1,0,0,1,1,0,0,0,0
1,2022,4,12,24,2.6,3.6,RTX 40 80,4,10,64,...,0,1,0,0,1,0,0,1,0,0
2,2024,2,8,16,2.6,3.6,RTX 40 50,1,4,8,...,0,0,0,0,1,1,0,0,0,0
3,2024,2,6,12,2.6,3.6,RX 7000 60,2,6,16,...,0,0,0,0,0,0,0,0,0,0
4,2024,5,16,32,2.8,3.9,RTX 30 80 Ti,5,12,96,...,0,0,0,0,1,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,2023,4,12,24,2.6,3.7,RX 7000 70,3,8,32,...,0,0,0,0,0,1,0,0,0,0
99996,2018,2,8,16,2.2,3.2,RX 6000 50,1,4,8,...,0,0,0,0,0,1,0,0,0,0
99997,2020,2,6,10,2.2,3.2,RTX 20 60,2,6,16,...,0,0,0,0,1,0,0,1,0,0
99998,2020,4,12,24,2.6,3.5,RTX 30 70,3,8,32,...,0,0,0,0,1,0,0,1,0,0
99999,2023,6,26,52,3.4,4.2,Arc A770 Limited,6,0,128,...,0,0,0,1,0,0,0,0,0,0