In [1]:
import pandas as pd
import numpy as np

np.random.seed(42)

In [2]:
def make_korean_name():
    sir = [
    '김', '이', '박', '최', '정', '강', '조', '윤', '장', '임',
    '한', '오', '서', '신', '권', '황', '안', '송', '류', '전',
    '홍', '고', '문', '양', '손', '배', '조', '백', '허', '유',
    '남', '심', '노', '하', '곽', '성', '차', '주', '우', '구',
    '신', '임', '나', '전', '민', '유', '진', '지', '엄', '채',
    '원', '천', '방', '공', '현', '함', '변', '염', '여', '추',
    '도', '소', '석', '선', '설', '마', '길', '연', '위', '표',
    '명', '기', '반', '왕', '금', '옥', '육', '인', '맹', '제',
    '모', '장', '남궁', '황보', '제갈', '독고', '선우', '서문',
    '동방', '어금', '망절', '사공', '탁', '빙', '판', '순', '견',
    '온', '변', '부', '봉', '빈', '상', '승', '삼', '운', '후',
    '묵', '점', '돈', '초', '궉', '요', '탄', '흥', '해', '교'
    ]
    
    name = [
        
    '가', '강', '건', '경', '고', '관', '광', '구', '규', '근',
    '기', '길', '나', '남', '다', '대', '도', '동', '두', '라',
    '래', '로', '루', '리', '린', '명', '무', '문', '미', '민',
    '범', '병', '보', '빛', '상', '서', '석', '선', '성', '세',
    '소', '솔', '수', '숙', '순', '승', '시', '신', '아', '애',
    '양', '연', '영', '예', '오', '옥', '완', '요', '용', '우',
    '욱', '원', '월', '위', '유', '윤', '은', '의', '이', '인',
    '일', '자', '재', '정', '제', '조', '주', '준', '중', '지',
    '진', '찬', '창', '채', '천', '철', '초', '춘', '치', '태',
    '하', '한', '해', '혁', '현', '혜', '호', '홍', '화', '환',
    '효', '훈', '희'
    ]
    
    arr_sir = np.array(sir)
    arr_name = np.array(name)
    
    return np.random.choice(arr_sir) + np.random.choice(arr_name) + np.random.choice(arr_name)

In [3]:
names = [make_korean_name() for _ in range(100)]
print(names)

['상연해', '권자욱', '홍희창', '선우제제', '서문환리', '박로영', '이춘민', '주강위', '추래보', '옥요로', '묵치아', '망절용솔', '사공우지', '권원원', '진원양', '묵오위', '박효양', '조래재', '우동경', '동방우남', '탄규태', '방강채', '사공우일', '전구시', '곽준진', '성애경', '이관예', '운경예', '탁월동', '어금숙빛', '왕원환', '신현신', '권자준', '선우원세', '제갈지찬', '초영리', '배치우', '점소미', '권순유', '동방일규', '서문가구', '서문월기', '흥진구', '곽상보', '정희소', '백광재', '기길빛', '노신루', '소춘석', '변숙철', '망절상유', '변효시', '인건가', '정태남', '상무규', '맹다태', '임주양', '석혜희', '요연혜', '최혁효', '문희다', '나미서', '서병일', '여철문', '마솔순', '소완관', '백문숙', '황보민원', '금한치', '상원호', '김무원', '해주건', '상인자', '조규원', '차호양', '운숙리', '맹용병', '순춘연', '요원요', '천길성', '이건효', '요옥진', '여강강', '사공예초', '봉혜호', '김두강', '방숙태', '심인병', '연오제', '함도선', '양이홍', '표철기', '궉대호', '반용인', '제해건', '전용서', '류태은', '류라혜', '명연보', '구성찬']

In [13]:
di = {
    '번호' : np.arange(1, 101), # 1 - 100까지 순차적인 값들의 배열 생성
    '이름' : names,
    '학년' : 3,
    '반' : np.random.randint(1, 6, size=100),   # 1 - 5까지 100개의 데이터 생성
    '국어' : np.clip(np.round(np.random.normal(40, 10, size=100), 2), 0, 100),    # 정규분포임
    '수학' : np.clip(np.round(np.random.normal(60, 10, size=100), 2), 0, 100),    # np.clip은 범위 밖으로 나가는 데이터를 잘라줌
    '영어' : np.clip(np.round(np.random.normal(70, 10, size=100), 2), 0, 100),
    '역사' : np.clip(np.round(np.random.normal(50, 10, size=100), 2), 0, 100),
}

df = pd.DataFrame(di)
df

     번호    이름  학년  반     국어     수학     영어     역사
0     1   상연해   3  3  22.37  77.93  78.86  40.13
1     2   권자욱   3  1  29.73  62.24  72.30  64.82
2     3   홍희창   3  3  42.47  51.95  91.05  47.47
3     4  선우제제   3  5  40.87  65.96  58.87  37.86
4     5  서문환리   3  4  47.02  62.71  82.22  40.36
..  ...   ...  .. ..    ...    ...    ...    ...
95   96   전용서   3  3  54.32  86.88  63.07  47.59
96   97   류태은   3  1  28.11  41.90  51.64  59.52
97   98   류라혜   3  5  37.45  53.12  81.71  61.01
98   99   명연보   3  4  40.33  74.74  85.86  45.90
99  100   구성찬   3  2  37.33  56.48  77.80  42.53

[100 rows x 8 columns]

In [ ]:
# 필터링하기
cond = df['역사'] > 100.0
df[cond]

Empty DataFrame
Columns: [번호, 이름, 학년, 반, 국어, 수학, 영어, 역사]
Index: []

In [19]:
# 국어 60점 이상, 영어 80점 이상인 학생들만 가져오기
cond = (df['국어'] >= 60.0) & (df['영어'] >= 80.0)
df[cond]

    번호    이름  학년  반    국어     수학     영어     역사
33  34  선우원세   3  1  60.1  48.79  97.31  35.14

In [ ]:
# 데이터 추가하기
# 총점이라는 데이터를 생성하여 컬럼을 추가함
df['총점'] = df['국어'] + df['수학'] + df['영어'] + df['역사']
df['평균'] = (df['총점'] / 4).round(2)
df.head()

   번호    이름  학년  반     국어     수학     영어     역사      총점       평균
0   1   상연해   3  3  22.37  77.93  78.86  40.13  219.29  54.8225
1   2   권자욱   3  1  29.73  62.24  72.30  64.82  229.09  57.2725
2   3   홍희창   3  3  42.47  51.95  91.05  47.47  232.94  58.2350
3   4  선우제제   3  5  40.87  65.96  58.87  37.86  203.56  50.8900
4   5  서문환리   3  4  47.02  62.71  82.22  40.36  232.31  58.0775

In [ ]:
# 100명 전체의 등수 구하기
df['석차'] = df['총점'].rank(ascending=False).astype(int)
df

     번호    이름  학년  반     국어     수학     영어     역사      총점       평균  석차
0     1   상연해   3  3  22.37  77.93  78.86  40.13  219.29  54.8225  48
1     2   권자욱   3  1  29.73  62.24  72.30  64.82  229.09  57.2725  34
2     3   홍희창   3  3  42.47  51.95  91.05  47.47  232.94  58.2350  28
3     4  선우제제   3  5  40.87  65.96  58.87  37.86  203.56  50.8900  84
4     5  서문환리   3  4  47.02  62.71  82.22  40.36  232.31  58.0775  31
..  ...   ...  .. ..    ...    ...    ...    ...     ...      ...  ..
95   96   전용서   3  3  54.32  86.88  63.07  47.59  251.86  62.9650   8
96   97   류태은   3  1  28.11  41.90  51.64  59.52  181.17  45.2925  97
97   98   류라혜   3  5  37.45  53.12  81.71  61.01  233.29  58.3225  27
98   99   명연보   3  4  40.33  74.74  85.86  45.90  246.83  61.7075   9
99  100   구성찬   3  2  37.33  56.48  77.80  42.53  214.14  53.5350  61

[100 rows x 11 columns]

In [32]:
# 데이터 정렬하기
df.sort_values(by='석차')

    번호   이름  학년  반     국어     수학     영어     역사      총점       평균   석차
82  83  여강강   3  4  42.98  69.02  78.55  77.16  267.71  66.9275    1
78  79  요원요   3  4  37.34  70.50  96.78  56.40  261.02  65.2550    2
16  17  박효양   3  3  31.92  65.46  92.91  68.91  259.20  64.8000    3
91  92  표철기   3  3  40.06  71.64  84.33  60.04  256.07  64.0175    4
38  39  권순유   3  3  53.97  73.76  61.14  65.73  254.60  63.6500    5
..  ..  ...  .. ..    ...    ...    ...    ...     ...      ...  ...
35  36  초영리   3  5  29.66  65.24  68.20  29.61  192.71  48.1775   96
96  97  류태은   3  1  28.11  41.90  51.64  59.52  181.17  45.2925   97
76  77  맹용병   3  4  48.34  43.94  53.03  35.52  180.83  45.2075   98
59  60  최혁효   3  2  39.95  50.57  47.91  37.24  175.67  43.9175   99
21  22  방강채   3  4  35.50  39.70  47.92  45.24  168.36  42.0900  100

[100 rows x 11 columns]

In [40]:
# 수학 경시대회에 차출될 3인의 명단을 데이터 프레임으로 만들어 제출하시오
#df.sort_values(by='수학', ascending=False)[0:3]
df.sort_values(by='수학', ascending=False).head(3)

    번호   이름  학년  반     국어     수학     영어     역사      총점       평균  석차
95  96  전용서   3  3  54.32  86.88  63.07  47.59  251.86  62.9650   8
6    7  이춘민   3  5  38.90  78.08  59.86  50.50  227.34  56.8350  36
0    1  상연해   3  3  22.37  77.93  78.86  40.13  219.29  54.8225  48